CREATE TABLE conversion_rate (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   rate DECIMAL NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   CONSTRAINT pk_conversionrate PRIMARY KEY (id)
);

ALTER TABLE conversion_rate ADD CONSTRAINT uc_conversionrate_name UNIQUE (name);